[package]
name = "next_episode"
version = "0.1.0"
authors = ["Athiwat Chunlakhan"]
description = "Find the next possible episode"
license = "Apache-2.0"

[dependencies]
lazy_static = "1.0.1"
regex = "1.0.0"
itertools = "0.7.8"
